"""Add timestamp and soft delete fields to User and Item models

Revision ID: 7206f14d0076
Revises: bee6a9d57d7c
Create Date: 2025-10-30 09:47:16.042030

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7206f14d0076'
down_revision = 'bee6a9d57d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('item', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('item', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('item', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_item_is_deleted'), 'item', ['is_deleted'], unique=False)
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_index(op.f('ix_item_is_deleted'), table_name='item')
    op.drop_column('item', 'is_deleted')
    op.drop_column('item', 'deleted_at')
    op.drop_column('item', 'updated_at')
    op.drop_column('item', 'created_at')
    # ### end Alembic commands ###
