"""Add role field to User model for RBAC

Revision ID: add_user_role_field
Revises: b295a26e82c2
Create Date: 2025-10-30 06:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_role_field'
down_revision = 'b295a26e82c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create UserRole enum type
    userrole_enum = sa.Enum('user', 'member', 'admin', name='userrole')
    userrole_enum.create(op.get_bind())

    # Add role column with default value 'user' for existing users
    op.add_column('user', sa.Column('role', userrole_enum, nullable=False, server_default='user'))
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    
    # Update existing superusers to have admin role
    op.execute("UPDATE \"user\" SET role = 'admin' WHERE is_superuser = true")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_column('user', 'role')
    # Drop enum type
    sa.Enum(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
