"""Add required tag field to Item with DEFAULT value

Revision ID: b295a26e82c2
Revises: 7206f14d0076
Create Date: 2025-10-30 11:38:17.093106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b295a26e82c2'
down_revision = '7206f14d0076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 首先创建枚举类型
    itemtag_enum = sa.Enum('default', 'economist', 'wsj', name='itemtag')
    itemtag_enum.create(op.get_bind())

    # 然后添加列，使用默认值处理现有数据
    op.add_column('item', sa.Column('tag', itemtag_enum, nullable=False, server_default='default'))
    op.create_index(op.f('ix_item_tag'), 'item', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_tag'), table_name='item')
    op.drop_column('item', 'tag')
    # 删除枚举类型
    sa.Enum(name='itemtag').drop(op.get_bind())
    # ### end Alembic commands ###
