"""Fix enum values to match Python definitions

Revision ID: b41054cc83e7
Revises: b295a26e82c2
Create Date: 2025-10-30 12:06:36.181954

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b41054cc83e7'
down_revision = 'b295a26e82c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建新的枚举类型
    new_itemtag_enum = sa.Enum('DEFAULT', 'ECONOMIST', 'WSJ', name='itemtag_new')
    new_itemtag_enum.create(op.get_bind())

    # 先删除默认值
    op.execute("ALTER TABLE item ALTER COLUMN tag DROP DEFAULT")

    # 修改列类型，使用新的枚举，同时转换数据
    op.execute("ALTER TABLE item ALTER COLUMN tag TYPE itemtag_new USING CASE tag WHEN 'default' THEN 'DEFAULT' WHEN 'economist' THEN 'ECONOMIST' WHEN 'wsj' THEN 'WSJ' END::itemtag_new")

    # 删除旧的枚举类型
    sa.Enum(name='itemtag').drop(op.get_bind(), checkfirst=False)

    # 重命名新枚举类型为原来的名称
    op.execute("ALTER TYPE itemtag_new RENAME TO itemtag")

    # 重新设置默认值
    op.execute("ALTER TABLE item ALTER COLUMN tag SET DEFAULT 'DEFAULT'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建小写枚举类型
    old_itemtag_enum = sa.Enum('default', 'economist', 'wsj', name='itemtag_old')
    old_itemtag_enum.create(op.get_bind())

    # 修改列类型，转换回小写值
    op.execute("ALTER TABLE item ALTER COLUMN tag TYPE itemtag_old USING CASE tag WHEN 'DEFAULT' THEN 'default' WHEN 'ECONOMIST' THEN 'economist' WHEN 'WSJ' THEN 'wsj' END::itemtag_old")

    # 删除大写枚举类型
    sa.Enum(name='itemtag').drop(op.get_bind(), checkfirst=False)

    # 重命名
    op.execute("ALTER TYPE itemtag_old RENAME TO itemtag")
    # ### end Alembic commands ###
